# .github/actions/my-action.yml
# Note the special trigger 'on: workflow_call:'

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      argument:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{inputs.os}}

    steps:
      - uses: actions/checkout@v2

      # ---------------------------------------------------
      # Dependencies
      - name: install dependencies / Ubuntu
        if: ${{ inputs.os == 'ubuntu-latest' }}
        run: |
          pip install numpy

      - name: Install dependencies / MacOS
        if: ${{ inputs.os == 'macos-latest' }}
        run: |
          brew install numpy

      # ---------------------------------------------------
      # Dummy
      - name: Echo
        env:
          argument: ${{ inputs.argument }}
        run: |
          echo "argument" $argument

      - name: Run python file
        run: python run.py
    