name: CMake

on:
  push:
  workflow_dispatch:
  pull_request_review:
    types: [ submitted ]

env:
  BUILD_TYPE: Release

jobs:

  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: stenczelt/actions-test/.github/actions/my-action
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.envPAT }}
