name: CMake

on:
  push:
  workflow_dispatch:
  pull_request_review:
    types: [ submitted ]

env:
  BUILD_TYPE: Release

jobs:

  reusable_workflow_job:
    uses: ./.github/actions/my-action/action.yml
    with:
      username: ${{ inputs.username }}
      token: ${{ secrets.envPAT }}
