name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
#      - uses: ./.github/actions/my-action
#        with:
#          username: ${{ inputs.username }}
#          token: ${{ secrets.token }}
      - name: check Python code with Black
        run: echo "Hello World!" ${{ inputs.username }}

      # NOT SUITABLE FOR PRODUCTION
      - name: check the 'secret' value
        run: echo ${{ secrets.CODECOV_TOKEN }}
